version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - mynetwork
  disease_prediction:
    build:
      context: ./backend/disease_prediction
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
